cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.7
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "^sd[b-z]$"
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                  - storage