name: Deploy Kubernetes Cluster

on:
  workflow_dispatch:

jobs:  
  deploy-api-server:
    runs-on: ubuntu-latest
    environment:
      name: deploy-api-server
    steps:
      - uses: actions/checkout@v4
      - name: Run kubectl commands
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl get nodes
          kubectl delete secret exosphere-api-server-secrets --ignore-not-found
          kubectl create secret generic exosphere-api-server-secrets --from-literal=MONGO_URI=${{ secrets.MONGO_URI }} --from-literal=MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }} --from-literal=JWT_SECRET_KEY=${{ secrets.JWT_SECRET }}

          cd k8s
          ls -la

          kubectl apply -f ./api-server-deployment.yaml
          kubectl apply -f ./api-server-service.yaml
          kubectl apply -f ./api-server-ingress.yaml

          helm upgrade --install traefik traefik/traefik --namespace traefik --create-namespace -f traefik-values.yaml

          helm repo add bitnami https://charts.bitnami.com/bitnami

          kubectl create namespace redis 
          kubectl -n redis create secret generic exosphere-redis-auth --from-literal=redis-password=${{ secrets.REDIS_PASSWORD }}
          helm upgrade --install redis bitnami/redis --namespace redis --create-namespace -f redis-values.yaml

          helm repo add rook-release https://charts.rook.io/release
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          helm upgrade --install rook-ceph rook-release/rook-ceph --namespace rook-ceph --create-namespace --version 1.17.6 --set enableDiscoveryDaemon=true --set crds.enabled=true

          helm upgrade --install rook-ceph-cluster rook-release/rook-ceph-cluster --namespace rook-ceph --version 1.17.6 -f rook-ceph-cluster-values.yaml

          kubectl -n rook-ceph apply -f https://raw.githubusercontent.com/rook/rook/v1.17.6/deploy/examples/toolbox.yaml

          
