name: Build & publish to PyPI

on:
  push: 
    branches:
      - main
    paths:
      - "python-sdk/**"
      - ".github/workflows/publish-python-sdk.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-sdk

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        name: Install uv

      - run: uv python install
     
      - run: uv sync --locked --dev

      - run: uv run python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
