name: State Manager Unit Tests

on:
  push:
    branches: [main]
    paths:
      - 'state-manager/**'
  pull_request:
    branches: [main]
    paths:
      - 'state-manager/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          cache: true

      - name: Install dev dependencies with uv
        working-directory: state-manager
        run: |
          uv sync --group dev

      - name: Run unit tests with pytest and coverage
        working-directory: state-manager
        run: |
          uv run pytest tests/unit/ --cov=app --cov-report=xml --cov-report=term-missing --cov-report=html -v --junitxml=unit-pytest-report.xml

      - name: Upload unit test coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: exospherehost/exospherehost
          files: state-manager/coverage.xml
          flags: state-manager-unit
          name: state-manager-unit-coverage-report
          fail_ci_if_error: true

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: state-manager-unit-test-results
          path: state-manager/unit-pytest-report.xml
          retention-days: 30

      - name: Upload unit test coverage HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: state-manager-unit-coverage-html
          path: state-manager/htmlcov/
          retention-days: 30
